@base_url=http://localhost:5000/api

### Token an userIs
@given_user_id=2e4f3ba4-fa49-42cf-b155-ce7dabfdc356
@givent_user_id2=f1d1f1c3-4b6e-4bf5-993c-a87b348d367c
@given_access_token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjgzT3Jxb0FhZnRWMy0teEk2a0JiR2ciLCJ0eXAiOiJhdCtqd3QifQ.eyJuYmYiOjE1ODc1NjU3MjYsImV4cCI6MTU4NzY1MjEyNiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAxIiwiYXVkIjoiYXBpMSIsImNsaWVudF9pZCI6IlRhc2tBUEkiLCJzdWIiOiIiLCJhdXRoX3RpbWUiOjE1ODc1NjU3MjYsImlkcCI6ImxvY2FsIiwidXNlcl9pZCI6IjJlNGYzYmE0LWZhNDktNDJjZi1iMTU1LWNlN2RhYmZkYzM1NiIsInVzZXJfZW1haWwiOiJhbnRvbi5hc25pdHNreUBnbWFpbC5jb20iLCJmaXJzdF9uYW1lIjoiQW50b24iLCJzdXJfbmFtZSI6IkFzbml0c2t5Iiwic2NvcGUiOlsiYXBpMSIsIm9mZmxpbmVfYWNjZXNzIl0sImFtciI6WyJwd2QiXX0.uu2q3Fu8R6fypkfKecX506ToJG7Y3ogBw5CdIf8A4BTKRhCwSjgoAsVW2O-BYIWWNSorIc-9c3DypY3eRe5H5yr8JtytDsVnx8Z1WwhkgOSoRwoWUb1O69Sf_glIrTUt_8oCWtvr5giwe45wTSgCJNYniXXlVnwq55xme3wm9RgNdsZVoVL9NWPllkr4HywjPvsIP3ucCgLVDz3JxRtEa1JZkrhQAk78uwV7ScUf_vCrmrUB4xce9eO951uOtMs1U7hu4c9a-mRpEKs1KYVC8q1hVzqJwAwudfem5xZ2M-FKRCLvJBqyBAx6rnDIdx2sxlc_kTJzmifM9CBf8v4AQQ

### Create new user
POST {{base_url}}/users
Accept: application/json
Content-Type: application/json

{
    "email": "marina.asnitsky@gmail.com",
    "password": "P@$$w0rD",
    "first_name": "Marina",
    "last_name": "Asnitsky",
    "phone": "+972523605291",
    "address": "10/59 Lachish st. Hadera Israel",
    "sex": 2
}


### Get users list
GET {{base_url}}/users
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{given_access_token}}

### Get single user
GET {{base_url}}/users/2e4f3ba4-fa49-42cf-b155-ce7dabfdc356
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{given_access_token}}


### Create new user
PUT {{base_url}}/users/{{given_user_id}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{given_access_token}}

{
    "first_name": "Moshe",
    "last_name": "Buzaglo",
    "phone": "+972541234567",
    "address": "12/70 Morning Star st. Horfesh Israel",
    "sex": 1
}

### Delete user
DELETE {{base_url}}/users/{{givent_user_id2}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{given_access_token}}